const PDFDocument = require('pdfkit');

const indigo = '#4f46e5';
const slate = '#334155';
const gray = '#64748b';
const green = '#059669';
const red = '#dc2626';

const addSectionHeading = (doc, text) => {
  doc.moveDown(0.8);
  doc.fontSize(12.5).fillColor(slate).font('Helvetica-Bold').text(text);
  doc.moveDown(0.3);
};

const addBulletList = (doc, items, color = gray) => {
  if (!items || items.length === 0) {
    doc.fontSize(10.5).fillColor(color).font('Helvetica').text('None found');
    return;
  }
  items.forEach((item) => {
    doc.fontSize(10.5).fillColor(color).font('Helvetica').text(`•  ${item}`, { indent: 4 });
  });
};

const generateReportPDF = (resume) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header bar
      doc.rect(0, 0, doc.page.width, 90).fill(indigo);
      doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text('AI Resume Analyzer', 50, 28);
      doc.fontSize(11).font('Helvetica').text('ATS Optimization Report', 50, 56);

      doc.moveDown(4.5);

      // File + role + date
      doc.fillColor(slate).fontSize(13).font('Helvetica-Bold').text(`File: ${resume.fileName}`);
      doc.fontSize(10.5).fillColor(gray).font('Helvetica')
        .text(`Target Role: ${resume.targetRole || 'General'}`)
        .text(`Generated: ${new Date(resume.createdAt || Date.now()).toLocaleString()}`);
      doc.moveDown(0.8);

      // Score
      const scoreColor = resume.atsScore >= 75 ? green : resume.atsScore >= 50 ? '#d97706' : red;
      doc.fontSize(16).fillColor(scoreColor).font('Helvetica-Bold').text(`ATS Match Score: ${resume.atsScore}%`);

      // Summary
      addSectionHeading(doc, 'Summary');
      doc.fontSize(10.5).fillColor(gray).font('Helvetica').text(resume.summary || 'N/A', { align: 'justify' });

      // Strengths
      addSectionHeading(doc, 'Strengths');
      addBulletList(doc, resume.strengths, green);

      // Improvement Areas
      addSectionHeading(doc, 'Improvement Areas');
      addBulletList(doc, resume.improvementAreas, red);

      // Missing Keywords
      addSectionHeading(doc, 'Missing Keywords');
      doc.fontSize(10.5).fillColor(gray).font('Helvetica').text(
        resume.missingKeywords && resume.missingKeywords.length ? resume.missingKeywords.join(', ') : 'None found'
      );

      // Formatting Issues
      addSectionHeading(doc, 'Formatting Issues');
      addBulletList(doc, resume.formattingIssues);

      // Actionable Tips
      addSectionHeading(doc, 'Actionable Tips');
      addBulletList(doc, resume.actionableTips, indigo);

      // Final Recommendation
      addSectionHeading(doc, 'Final Recommendation');
      doc.fontSize(10.5).fillColor(slate).font('Helvetica-Bold').text(resume.finalRecommendation || 'N/A', { align: 'justify' });

      // Footer
      doc.fontSize(8).fillColor('#94a3b8').text(
        'Generated by AI Resume Analyzer',
        50,
        doc.page.height - 40,
        { align: 'center' }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateReportPDF };